/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AirAvatar {
        "bgColor": string;
        "name": string;
        "rounded": boolean;
        "size": string;
    }
    interface AirButton {
        "color": | "default"
    | "primary"
    | "success"
    | "info"
    | "warning"
    | "danger"
    | "ghost";
        "disabled": boolean;
        "icon": string;
        "loading": boolean;
        "selected": boolean;
        "size": "small" | "medium" | "large";
        "suffixIcon": string;
        "variant": | "solid"
    | "outline"
    | "text"
    | "neo"
    | "default";
    }
    interface AirButtonGroup {
        "customStyles": { [key: string]: string };
        "direction": "horizontal" | "vertical";
        "group": string;
        "spacing": string;
    }
    interface AirCard {
        "content": string;
        "imageUrl": string;
        "isHighlighted": boolean;
        "size": 'small' | 'medium' | 'large';
        "title": string;
    }
    /**
     * @name AirIcon
     * @description Icons are visual symbols used to represent ideas, objects, or actions.
     * @overview Icons are visual symbols used to represent ideas, objects, or actions. They communicate messages at a glance, afford interactivity, and draw attention to important information.
     * @category General
     * @example <air-icon name="home" size="2rem" />
     */
    interface AirIcon {
        /**
          * Custom CSS class to apply to the icon.
         */
        "customClass": string;
        /**
          * Custom CSS style to apply to the icon.
         */
        "customStyle": { [key: string]: string } | string;
        /**
          * The identifier for the icon. This name corresponds to a specific SVG asset in the icon set.
         */
        "name": string;
        /**
          * The size of the icon. This can be specified in pixels (px) or rem units to control the icon's dimensions. If a number is provided, it will be treated as rem units. For example, '16px', '2rem', or 2 would be valid values.
         */
        "size": string;
    }
    /**
     * @name AirText
     * @description Typography for rendering headlines, paragraphs, captions, and body text with various style options.
     * @category General
     * @example <air-text type="heading" level="1">Heading</air-text>
     */
    interface AirText {
        "color": | 'primary'
      | 'secondary'
      | 'tertiary'
      | 'helper'
      | 'error'
      | 'on-color'
      | 'inverse';
        "configAria": any;
        "expressive": boolean;
        "headingLevel": 1 | 2 | 3 | 4 | 5 | 6;
        "headingSize": 1 | 2 | 3 | 4 | 5 | 6 | 7;
        "inline": boolean;
        "type": | 'code'
      | 'helper-text'
      | 'label'
      | 'legal'
      | 'heading'
      | 'body'
      | 'body-compact'
      | 'body-large'
      | 'body-emphasis'
      | 'fluid-heading';
    }
}
export interface AirButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAirButtonElement;
}
export interface AirCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAirCardElement;
}
export interface AirIconCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAirIconElement;
}
declare global {
    interface HTMLAirAvatarElement extends Components.AirAvatar, HTMLStencilElement {
    }
    var HTMLAirAvatarElement: {
        prototype: HTMLAirAvatarElement;
        new (): HTMLAirAvatarElement;
    };
    interface HTMLAirButtonElementEventMap {
        "buttonClick": { event: MouseEvent; selected: boolean };
    }
    interface HTMLAirButtonElement extends Components.AirButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAirButtonElementEventMap>(type: K, listener: (this: HTMLAirButtonElement, ev: AirButtonCustomEvent<HTMLAirButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAirButtonElementEventMap>(type: K, listener: (this: HTMLAirButtonElement, ev: AirButtonCustomEvent<HTMLAirButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAirButtonElement: {
        prototype: HTMLAirButtonElement;
        new (): HTMLAirButtonElement;
    };
    interface HTMLAirButtonGroupElement extends Components.AirButtonGroup, HTMLStencilElement {
    }
    var HTMLAirButtonGroupElement: {
        prototype: HTMLAirButtonGroupElement;
        new (): HTMLAirButtonGroupElement;
    };
    interface HTMLAirCardElementEventMap {
        "cardClicked": void;
    }
    interface HTMLAirCardElement extends Components.AirCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAirCardElementEventMap>(type: K, listener: (this: HTMLAirCardElement, ev: AirCardCustomEvent<HTMLAirCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAirCardElementEventMap>(type: K, listener: (this: HTMLAirCardElement, ev: AirCardCustomEvent<HTMLAirCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAirCardElement: {
        prototype: HTMLAirCardElement;
        new (): HTMLAirCardElement;
    };
    interface HTMLAirIconElementEventMap {
        "iconClicked": any;
    }
    /**
     * @name AirIcon
     * @description Icons are visual symbols used to represent ideas, objects, or actions.
     * @overview Icons are visual symbols used to represent ideas, objects, or actions. They communicate messages at a glance, afford interactivity, and draw attention to important information.
     * @category General
     * @example <air-icon name="home" size="2rem" />
     */
    interface HTMLAirIconElement extends Components.AirIcon, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAirIconElementEventMap>(type: K, listener: (this: HTMLAirIconElement, ev: AirIconCustomEvent<HTMLAirIconElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAirIconElementEventMap>(type: K, listener: (this: HTMLAirIconElement, ev: AirIconCustomEvent<HTMLAirIconElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAirIconElement: {
        prototype: HTMLAirIconElement;
        new (): HTMLAirIconElement;
    };
    /**
     * @name AirText
     * @description Typography for rendering headlines, paragraphs, captions, and body text with various style options.
     * @category General
     * @example <air-text type="heading" level="1">Heading</air-text>
     */
    interface HTMLAirTextElement extends Components.AirText, HTMLStencilElement {
    }
    var HTMLAirTextElement: {
        prototype: HTMLAirTextElement;
        new (): HTMLAirTextElement;
    };
    interface HTMLElementTagNameMap {
        "air-avatar": HTMLAirAvatarElement;
        "air-button": HTMLAirButtonElement;
        "air-button-group": HTMLAirButtonGroupElement;
        "air-card": HTMLAirCardElement;
        "air-icon": HTMLAirIconElement;
        "air-text": HTMLAirTextElement;
    }
}
declare namespace LocalJSX {
    interface AirAvatar {
        "bgColor"?: string;
        "name"?: string;
        "rounded"?: boolean;
        "size"?: string;
    }
    interface AirButton {
        "color"?: | "default"
    | "primary"
    | "success"
    | "info"
    | "warning"
    | "danger"
    | "ghost";
        "disabled"?: boolean;
        "icon"?: string;
        "loading"?: boolean;
        "onButtonClick"?: (event: AirButtonCustomEvent<{ event: MouseEvent; selected: boolean }>) => void;
        "selected"?: boolean;
        "size"?: "small" | "medium" | "large";
        "suffixIcon"?: string;
        "variant"?: | "solid"
    | "outline"
    | "text"
    | "neo"
    | "default";
    }
    interface AirButtonGroup {
        "customStyles"?: { [key: string]: string };
        "direction"?: "horizontal" | "vertical";
        "group"?: string;
        "spacing"?: string;
    }
    interface AirCard {
        "content"?: string;
        "imageUrl"?: string;
        "isHighlighted"?: boolean;
        "onCardClicked"?: (event: AirCardCustomEvent<void>) => void;
        "size"?: 'small' | 'medium' | 'large';
        "title"?: string;
    }
    /**
     * @name AirIcon
     * @description Icons are visual symbols used to represent ideas, objects, or actions.
     * @overview Icons are visual symbols used to represent ideas, objects, or actions. They communicate messages at a glance, afford interactivity, and draw attention to important information.
     * @category General
     * @example <air-icon name="home" size="2rem" />
     */
    interface AirIcon {
        /**
          * Custom CSS class to apply to the icon.
         */
        "customClass"?: string;
        /**
          * Custom CSS style to apply to the icon.
         */
        "customStyle"?: { [key: string]: string } | string;
        /**
          * The identifier for the icon. This name corresponds to a specific SVG asset in the icon set.
         */
        "name"?: string;
        /**
          * The event fired when the icon is clicked.
         */
        "onIconClicked"?: (event: AirIconCustomEvent<any>) => void;
        /**
          * The size of the icon. This can be specified in pixels (px) or rem units to control the icon's dimensions. If a number is provided, it will be treated as rem units. For example, '16px', '2rem', or 2 would be valid values.
         */
        "size"?: string;
    }
    /**
     * @name AirText
     * @description Typography for rendering headlines, paragraphs, captions, and body text with various style options.
     * @category General
     * @example <air-text type="heading" level="1">Heading</air-text>
     */
    interface AirText {
        "color"?: | 'primary'
      | 'secondary'
      | 'tertiary'
      | 'helper'
      | 'error'
      | 'on-color'
      | 'inverse';
        "configAria"?: any;
        "expressive"?: boolean;
        "headingLevel"?: 1 | 2 | 3 | 4 | 5 | 6;
        "headingSize"?: 1 | 2 | 3 | 4 | 5 | 6 | 7;
        "inline"?: boolean;
        "type"?: | 'code'
      | 'helper-text'
      | 'label'
      | 'legal'
      | 'heading'
      | 'body'
      | 'body-compact'
      | 'body-large'
      | 'body-emphasis'
      | 'fluid-heading';
    }
    interface IntrinsicElements {
        "air-avatar": AirAvatar;
        "air-button": AirButton;
        "air-button-group": AirButtonGroup;
        "air-card": AirCard;
        "air-icon": AirIcon;
        "air-text": AirText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "air-avatar": LocalJSX.AirAvatar & JSXBase.HTMLAttributes<HTMLAirAvatarElement>;
            "air-button": LocalJSX.AirButton & JSXBase.HTMLAttributes<HTMLAirButtonElement>;
            "air-button-group": LocalJSX.AirButtonGroup & JSXBase.HTMLAttributes<HTMLAirButtonGroupElement>;
            "air-card": LocalJSX.AirCard & JSXBase.HTMLAttributes<HTMLAirCardElement>;
            /**
             * @name AirIcon
             * @description Icons are visual symbols used to represent ideas, objects, or actions.
             * @overview Icons are visual symbols used to represent ideas, objects, or actions. They communicate messages at a glance, afford interactivity, and draw attention to important information.
             * @category General
             * @example <air-icon name="home" size="2rem" />
             */
            "air-icon": LocalJSX.AirIcon & JSXBase.HTMLAttributes<HTMLAirIconElement>;
            /**
             * @name AirText
             * @description Typography for rendering headlines, paragraphs, captions, and body text with various style options.
             * @category General
             * @example <air-text type="heading" level="1">Heading</air-text>
             */
            "air-text": LocalJSX.AirText & JSXBase.HTMLAttributes<HTMLAirTextElement>;
        }
    }
}
